---
title: "Simple Report"
author: ""
date: '`r Sys.Date()`'
output:
  html_document:
    css: "css/style.css"
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options:
  chunk_output_type: console
---

```{r library, message = FALSE, results = 'hide', echo = FALSE}
knitr::opts_chunk$set(
  # echo = FALSE,
  message = FALSE,
  warning = FALSE)
# rm(list = ls())
library(trySimulation)

library(tidyverse)
library(knitr)
library(kableExtra)

root <- rprojroot::find_rstudio_root_file()
result_path <- file.path(root, ".simulation")

load(file.path(result_path, "results.rdata"))
# ls()
```


## Introduction

연습용 시뮬레이션.

## Method

$$\Sigma =  \Lambda \Phi \Lambda^{\\'} + \Psi$$

$$
\begin{aligned}
\Sigma &= \left(\begin{array}{cc} 
\Sigma_{yy} & sym\\
\Sigma_{xy} & \Sigma_{xx}
\end{array}\right) \\
&= \left(\begin{array}{cc} 
\Lambda_y(I-B)^{-1}(\Gamma\Phi\Gamma^{\\'}+\Psi)(I-B)^{\\'-1}\Lambda_y + \Theta_\epsilon & \Lambda_y(I-B)^{-1}\Gamma\Phi\Lambda^{\\'}\\
\Lambda_x\Phi\Gamma^{\\'}(I-B)^{-1}\Lambda^{\\'}_y &
\Lambda_x\Phi\Lambda^{\\'}_x+\Theta_\delta
\end{array}\right)
\end{aligned}
$$ 



```{r}
makeCondition(n_sample = c(100, 500), cov_size = c(0, 0.5), n_indi = c(3, 6), cut_size = c(3,5,7), n_rep = 5, full = F) %>% 
 kable(., format="markdown", digits=4) 
```


## Results

```{r}
makePlot(bias_res, what = "RMSE", font_size = 12)
```

```{r}
makePlot(power_res, what = "power", font_size = 12)
```

```{r}
makePlot(power_res, what = "typeIerror", font_size = 12)
```


