---
title: "Simple Report"
author: ""
date: '`r Sys.Date()`'
output:
  html_document:
    css: "style.css"
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options:
  chunk_output_type: console
---

```{r library, message = FALSE, results = 'hide', echo = FALSE}
knitr::opts_chunk$set(
  # echo = FALSE,
  message = FALSE,
  warning = FALSE)
# rm(list = ls())
library(trySimulation)

library(tidyverse)
library(knitr)
library(kableExtra)

root <- rprojroot::find_rstudio_root_file()
report_path <- file.path(root, ".simulation")

load(file.path(report_path, "results.rdata"))
# ls()
```


## Introduction

연습용 시뮬레이션.

## Method

$$\Sigma =  \Lambda \Phi \Lambda^T + \Psi$$

```{r}
makeCondition(n_sample = c(100, 500), cov_size = c(0, 0.5), n_indi = c(3, 6), cut_size = c(3,5,7), n_rep = 5, full = F) %>% 
 kable(., format="markdown", digits=4) 
```


## Results

```{r}
makePlot(bias_res, what = "RMSE", font_size = 12)
```

```{r}
makePlot(power_res, what = "power", font_size = 12)
```

```{r}
makePlot(power_res, what = "typeIerror", font_size = 12)
```


